version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: nexis-postgres
    restart: always
    environment:
      POSTGRES_USER: nexis
      POSTGRES_PASSWORD: nexispassword
      POSTGRES_DB: nexisdb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
